source 'https://rubygems.org'
gem 'rails', '3.2.13'

gem 'jquery-rails'
gem 'facebox-rails'
gem 'haml-rails', '>= 0.4'
gem 'parsley-rails'
#gem 'fullcalendar-rails'

gem "mongoid", ">= 3.1.2"
gem "haml-rails", ">= 0.4"
gem "figaro", ">= 0.6.3"

gem 'devise', '>= 2.2.3'
gem 'cancan', '>= 1.6.8'
gem 'rolify', '>= 3.2.0'

gem 'simple_form', '>= 2.0.4'
gem 'faker'
#gem 'paperclip'
gem "mongoid-paperclip", :require => "mongoid_paperclip"

gem 'aws-ses', '~> 0.4.4', :require => 'aws/ses'
gem 'aws-s3'
gem 'aws-sdk'
gem 'omniauth', '>= 1.1.0'
gem 'omniauth-facebook'

gem "stripe", ">= 1.7.11"
gem "stripe_event", ">= 0.4.0"
gem 'paypal-express'
gem 'rails-bootstrap-toggle-buttons', '~> 0.0.7'

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
  gem "therubyracer", ">= 0.11.3", :platform => :ruby, :require => "v8"
  gem 'bootstrap-sass'
  gem 'twitter-bootstrap-rails'
end

group :development do
	gem "html2haml", ">= 1.0.1"
	gem "rspec-rails", ">= 2.12.2"
	gem "factory_girl_rails", ">= 4.2.0"
	gem "quiet_assets", ">= 1.0.2"
	gem "better_errors", ">= 0.7.2"
	gem "binding_of_caller", ">= 0.7.1", :platforms => [:mri_19, :rbx]
	gem 'webrick'
end
group :test do
	gem "rspec-rails", ">= 2.12.2"
	gem "database_cleaner", ">= 1.0.0.RC1"
	gem "mongoid-rspec", ">= 1.7.0"
	gem "email_spec", ">= 1.4.0"
	gem "cucumber-rails", ">= 1.3.1", :require => false
	gem "factory_girl_rails", ">= 4.2.0"
	gem "launchy", ">= 2.2.0"
	gem "capybara", ">= 2.0.3"
end

group :production do
end