source 'https://rubygems.org'
gem 'rails', '3.2.11'
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
  gem 'therubyracer', :platforms => :ruby
end

gem 'jquery-rails'
gem 'jquery-fileupload-rails'
gem 'paperclip'
gem 'twitter-bootstrap-rails'
# gem 'haml-rails'
gem 'rack-maintenance'
gem "unicorn", ">= 4.3.1", :group => :production
gem "mongoid", "3.0.19"
gem "rspec-rails", ">= 2.11.4", :group => [:development, :test]
gem "capybara", ">= 1.1.3", :group => :test
gem "database_cleaner", ">= 0.9.1", :group => :test
gem "mongoid-rspec", ">= 1.4.6", :group => :test
gem "email_spec", ">= 1.4.0", :group => :test
gem "factory_girl_rails", ">= 4.1.0", :group => [:development, :test]
gem "bootstrap-sass", ">= 2.1.1.0"
gem "hominid", ">= 3.0.5"
gem "devise", ">= 2.1.2"
gem "cancan", ">= 1.6.8"
gem "rolify", ">= 3.2.0"
gem "simple_form", ">= 2.0.4"
gem "quiet_assets", ">= 1.0.1", :group => :development
gem "hub", ">= 1.10.2", :require => nil, :group => [:development]

gem 'markerb', '0.1.0'

gem 'fog', '1.7.0'
gem "carrierwave-mongoid", :git => "git://github.com/jnicklas/carrierwave-mongoid.git", :branch => "mongoid-3.0"
#gem 'carrierwave-mongoid', '0.1.0', require: 'carrierwave/mongoid'
gem 'flash_cookie_session', '1.1.1'
gem 'streamio-ffmpeg', '0.9.0'
gem 'rmagick', '2.13.1'

gem 'remail', '0.0.3'
gem 'letter_opener'
gem 'roadie'
gem 'exception_notification', :require => 'exception_notifier'
gem 'mongoid_search', '~> 0.2.8'
gem 'rails-footnotes', '>= 3.7.5.rc4', :group => :development
gem 'rails_admin'
