#!/usr/bin/env rake
# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require File.expand_path('../config/application', __FILE__)

Web::Application.load_tasks

if defined? YARD
  YARD_PATHS = ["spec/**/*_spec.rb","lib/**/*.rb","app/**/*.rb","db/schema.rb"]
  
  require 'yard' 
  require File.dirname(__FILE__) + '/lib/doc/yard_extensions'

  YARD::Rake::YardocTask.new do |t|
    t.files   = [YARD_PATHS]   # optional
  end
end