class Option < ActiveRecord::Base
  attr_accessible :option_name, :option_value, :picture_attributes

  has_one :picture, :as => :imageable, :dependent => :destroy
  accepts_nested_attributes_for :picture, :allow_destroy=>true, :reject_if => :all_blank

  STATES = [
  	['Alabama'],
		['Alaska'],
		['Arizona'],
		['Arkansas'],
		['California'],
		['Colorado'],
		['Connecticut'],
		['Delaware'],
		['Florida'],
		['Georgia'],
		['Hawaii'],
		['Idaho'],
		['Illinois'],
		['Indiana'],
		['Iowa'],
		['Kansas'],
		['Kentucky'],
		['Louisiana'],
		['Maine'],
		['Maryland'],
		['Massachusetts'],
		['Michigan'],
		['Minnesota'],
		['Mississippi'],
		['Missouri'],
		['Montana'],
		['Nebraska'],
		['Nevada'],
		['New Hampshire'],
		['New Jersey'],
		['New Mexico'],
		['New York'],
		['North Carolina'],
		['North Dakota'],
		['Ohio'],
		['Oklahoma'],
		['Oregon'],
		['Pennsylvania'],
		['Rhode Island'],
		['South Carolina'],
		['South Dakota'],
		['Tennessee'],
		['Texas'],
		['Utah'],
		['Vermont'],
		['Virginia'],
		['Washington'],
		['West Virginia'],
		['Wisconsin'],
		['Wyoming']]
end
