source 'https://rubygems.org'

ruby '2.1.1'
# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.0.2'

gem 'thin'
# Use postgresql as the database for Active Record
gem 'pg'

gem 'devise'
gem 'haml-rails'
gem 'haml2slim'
gem 'html2haml'

# Use simple form for frontend
#gem 'simple_form', '>= 3.0.0.rc'
gem 'simple_form'
# Use the bootstrap for frontend
#gem 'bootstrap-sass', '~> 2.3.2.2'

group :assets do  
  # Use SCSS for stylesheets
  gem 'sass-rails', '~> 4.0.0'

  # Use LESS for stylesheets
  gem 'therubyracer'
  gem 'less-rails'
  # gem 'twitter-bootstrap-rails'
  # Use Uglifier as compressor for JavaScript assets
  gem 'uglifier', '>= 1.3.0'

  # Use CoffeeScript for .js.coffee assets and views
  gem 'coffee-rails', '~> 4.0.0'

end


# Use jquery as the JavaScript library
gem 'jquery-rails'

# Use parsley-rails 
gem 'parsley-rails'

# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 1.2'

group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', require: false
end

gem 'rails_12factor', group: :production

group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'hub', :require=>nil
  gem 'quiet_assets'
  gem 'rails_layout'
  gem 'debugger'
  gem 'letter_opener'
  
  #gem 'rails-erd'
end

group :test do
  gem 'database_cleaner', '1.0.1'
end