source 'https://rubygems.org'
gem 'rails', '3.2.13'
gem 'jquery-rails'
gem 'colorbox-rails'
gem "haml-rails", ">= 0.4"
gem "rspec-rails", ">= 2.12.2", :group => [:development, :test]
gem "factory_girl_rails", ">= 4.2.0", :group => [:development, :test]
gem "bootstrap-sass", ">= 2.3.0.0"
gem "devise", ">= 2.2.3"
gem "devise_invitable"
gem "cancan", ">= 1.6.9"
gem "rolify", ">= 3.2.0"
gem "simple_form", ">= 2.1.0"
gem "stripe", ">= 1.7.11"
gem "stripe_event", ">= 0.4.0"
gem 'paypal-express'
gem "figaro", ">= 0.6.3"

gem "libv8", ">= 3.11.8"
gem 'twitter-bootstrap-rails'

gem "country_select"
gem "rmagick"
gem "paperclip", "~> 3.0"
gem 'activeadmin'
gem 'meta_search'
gem 'pusher'
gem 'recaptcha', :require => 'recaptcha/rails'
gem 'mailboxer'

gem "will_paginate", ">=3.0.pre2"
gem 'will_paginate_twitter_bootstrap'

group :assets do
	gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
  gem 'therubyracer', :platforms => :ruby  
end
group :test do
	gem "database_cleaner"
	gem "email_spec"
	gem "cucumber-rails"
	gem "launchy"	
	gem "capybara"
end
group :development do
  gem 'sqlite3'
  gem "html2haml"
  gem "quiet_assets"
  gem "better_errors"
  gem "binding_of_caller"
  gem 'webrick'
end

group :production do
  gem 'pg'
end
