source 'https://rubygems.org'

gem 'rails', '3.2.11'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'less-rails'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  gem 'therubyracer', :platforms => :ruby
  gem 'twitter-bootstrap-rails'
  gem 'bootstrap-sass'
  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'haml-rails'
gem "will_paginate", ">=3.0.pre2"
gem 'will_paginate_twitter_bootstrap'

gem 'kaminari'
#gem 'json_builder'
#gem 'json', '>= 1.4.6'
#gem 'metropoli', :git => 'git://github.com/innku/metropoli.git'
#gem 'messaging', git: 'git://github.com/frodefi/rails-messaging.git'
gem 'mailboxer'

gem 'devise'

gem 'rmagick'
gem 'recaptcha'

gem 'rails_tokeninput'
gem 'rails3-jquery-autocomplete'
gem 'parsley-rails'

gem 'googlecharts', :require => "gchart"
gem 'ajaxful_rating', :git => "git://github.com/edgarjs/ajaxful-rating.git", :branch => 'rails3'
gem 'acts_as_commentable_with_threading'

gem 'twitter-bootstrap-form-builder'
gem 'simple_form'

gem 'fastercsv'
#gem 'rails_admin'
gem 'activeadmin'

gem 'delayed_job'
gem 'delayed_job_active_record'

gem 'paperclip'
gem 'redcarpet'
gem 'albino'
gem 'nokogiri'

gem 'thin'
group :development do
  # gem 'pg'
  gem 'sqlite3'
  gem 'hirb'
  gem "quiet_assets"
  gem "better_errors"
  gem "binding_of_caller"
  gem 'webrick'
  gem 'letter_opener'
end

group :production do
  gem 'pg'
end
