source 'https://rubygems.org'
ruby "1.9.3"
gem 'rails', '3.2.17'

gem 'thin'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'
gem 'devise'
gem 'haml-rails'
gem 'haml2slim'
gem 'html2haml'

gem 'pg'

# Use simple form for frontend
#gem 'simple_form', '>= 3.0.0.rc'
gem 'simple_form'
# Use the bootstrap for frontend
gem 'bootstrap-sass', '~> 2.3.2.2'

# Gems used only for assets and not required
# in production environments by default.

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platforms => :ruby

  gem 'uglifier', '>= 1.0.3'
end

# Use jquery as the JavaScript library
gem 'jquery-rails'

# Use parsley-rails 
gem 'parsley-rails'

# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 1.2'

#Use Grape for API
gem 'grape'
gem 'grape-swagger'
# For pushnotification
gem 'pushmeup'

# For geolocation
gem 'geocoder'
gem 'redis'

gem 'rails_12factor', group: :production


group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', require: false
end



group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'hub', :require=>nil
  gem 'quiet_assets'
  gem 'rails_layout'
  gem 'debugger'
  gem 'letter_opener'
  
  #gem 'rails-erd'
end

group :test do
  gem 'database_cleaner', '1.0.1'
end

group :development, :test do
  gem 'thin'

  gem 'pry'
  gem 'factory_girl_rails'
  gem 'rspec-rails'
  gem 'sqlite3'
end